### PR TITLE
Unsticky OH navbar

### PR DESCRIPTION
**Pull request by chrononyan**
For various reasons, the navbar can become multiple lines. Rather than trying to make more screen-width breakpoints or extra padding, unstickying the navbar makes it so that no overlap happens in the first place.

Static navbar makes it so people have to scroll up to reach its links, but I think this is generally not a huge issue.

image

### CODE REVIEW

**Comment by rahularya50** [comment]
Wait wait actually, can you just add more width breakpoints? I'm not a fan of a multiline navbar

**Comment by chrononyan** [comment]
Names are variable-length though, so moving the breakpoint around means either the navbar collapses unnecessarily on large screens, or people with longer names get multi-line anyway. Or we could remove the name from the navbar and make it "Profile" or something

**Comment by rahularya50** [comment]
image
uhhhh

**Review by rahularya50 — CHANGES_REQUESTED** [review]
breaks jumbotron

**Pull request closed without merging**
